### PR TITLE
Fix issue with loading persisted cluster configuration from disk when a cluster change occurred

### PR DESCRIPTION
**Pull request by simontherry**
Consider the following scenario:
- Start a few RAFT nodes which are not clustered
- Use AddMemberAsync to pair them and ApplyAsync to save it to disk
- Kill the nodes and restart them, the configuration is lost.

Fix implemented in the write to the filestream.

Expanded applicable unit test.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/dotNext?pullRequest=106) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/dotNext?pullRequest=106) before we can accept your contribution.<br/><br/>:x: simontherry [sign now](https://cla.dotnetfoundation.org/dotnet/dotNext?pullRequest=106)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/dotNext?pullRequest=106) it.</sub>

**Comment by sakno** [comment]
Hi @simontherry , could you change the target branch from `master` to `develop` according to [Contribution](https://github.com/dotnet/dotNext/blob/master/CONTRIBUTING.md) guideline?

**Comment by simontherry** [comment]
@sakno My bad, overlooked this. Edited.

**Comment by simontherry** [comment]
Correct PR in #107

**Pull request closed without merging**
